version: '3.9'

services:

    mongo:
        container_name: mongo
        image: mongo:4.4.6
        ports:
        - "27017:27017"

    web:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - mongo
        links:
          - mongo